### ISSUE TITLE
It shouldn't run getPath(process.argv[2]) when imported

### ISSUE THREAD

**Issue by fregu** [lexoyo/node_modules-path#1]
Just by importing this package as a dependency, I get a long stack of failed node_module paths since it always runs even if not invoked in node.

Otherwise it is exactly what I am looking for.

Recommend moving CLI logic to separate file bin.js instead.

**Comment by lexoyo** [comment]
Hello @fregu 
You mean when you do this 
```
const node_modules = require('node_modules-path');
```
It starts scanning folders?
It is not supposed to, let me check

**Comment by lexoyo** [comment]
Ok you're right
I never noticed that 🤕 
[This technique](https://codewithhugo.com/node-module-entry-required/) is probably what I should use, what do you think?

**Comment by fregu** [comment]
I’m never sure about those methods of checking, and is not sure if they still works with ES-,module import.

I’ve created a PR where I move the CLI logic to a separate file bin.js instead
https://github.com/lexoyo/node_modules-path/pull/2/files

**Comment by lexoyo** [comment]
> Recommend moving CLI logic to separate file bin.js instead.

I just read that
Yes you're right it's even simpler
I'll do this soon
Feel free to do a PR, I'll merge it very quickly and publish on npm
Otherwise I will do it as soon as I have time, probably this week

**Comment by lexoyo** [comment]
it's published on npm
thx
