### ISSUE TITLE
Why lower than 18.0.0? 

### ISSUE THREAD

**Issue by maktouch** [lexoyo/node_modules-path#3]
https://github.com/lexoyo/node_modules-path/blob/d29aa4672a7a1a8b2af4c04b1a1206766f5fed96/package.json#L10

Is there a reason why it shouldn't work on 18.0.2?

**Comment by lexoyo** [comment]
Hello
I'm not sure if I tested and it didn't work or if I didn't test at all :/
Would you test it and I raise to 19? Or you can make a PR if you find out that it works?

**Comment by maktouch** [comment]
imho we should only keep the `"node": ">=10.15.3"`. it also works on 18.9, and I don't think they'll introduce breaking changes.

**Comment by lexoyo** [comment]
FYI it's been automatically published on npm
